version: 2

jobs:
  linux:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run:
          name: Debug build
          command: swift build
      - run:
          name: Run unit tests
          command: swift test

  linux-latest:
    docker:
      - image: swift:latest
    steps:
      - checkout
      - run:
          name: Debug build
          command: swift build
      - run:
          name: Run unit tests
          command: swift test

  linux-release:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run:
          name: Release build
          command: swift build -c release

workflows:
  version: 2
  build_and_test:
    jobs:
      - linux
      - linux-latest
      - linux-release
