version: 2
jobs:
  test:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run: swift build
      - run: swift test
  test-latest:
    docker:
      - image: swift:latest
    steps:
      - checkout
      - run: swift build
      - run: swift test
  build-release:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run: swift build -c release

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - test-latest
      - build-release
